declare module "lucide-react" {
  import type { ComponentType, SVGProps } from "react";

  export type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & {
    size?: string | number;
    strokeWidth?: string | number;
    absoluteStrokeWidth?: boolean;
  }>;

  export const AlertTriangle: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowRightLeft: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const BadgeDollarSign: LucideIcon;
  export const Bot: LucideIcon;
  export const Calculator: LucideIcon;
  export const Check: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Circle: LucideIcon;
  export const CircleAlert: LucideIcon;
  export const CircleDollarSign: LucideIcon;
  export const CircleHelp: LucideIcon;
  export const Clock3: LucideIcon;
  export const Download: LucideIcon;
  export const Edit3: LucideIcon;
  export const Eye: LucideIcon;
  export const FileArchive: LucideIcon;
  export const FileCheck: LucideIcon;
  export const FileCheck2: LucideIcon;
  export const FileInput: LucideIcon;
  export const FileJson: LucideIcon;
  export const FileSearch: LucideIcon;
  export const FileSpreadsheet: LucideIcon;
  export const FileText: LucideIcon;
  export const FlaskConical: LucideIcon;
  export const Folder: LucideIcon;
  export const GitBranch: LucideIcon;
  export const GripVertical: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const History: LucideIcon;
  export const Inbox: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const ListChecks: LucideIcon;
  export const LoaderCircle: LucideIcon;
  export const LogOut: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Network: LucideIcon;
  export const Orbit: LucideIcon;
  export const PackageCheck: LucideIcon;
  export const Paperclip: LucideIcon;
  export const PanelRight: LucideIcon;
  export const Pin: LucideIcon;
  export const PinOff: LucideIcon;
  export const Plus: LucideIcon;
  export const ReceiptText: LucideIcon;
  export const Search: LucideIcon;
  export const SearchCheck: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Settings2: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const SlidersHorizontal: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Trash2: LucideIcon;
  export const TriangleAlert: LucideIcon;
  export const Upload: LucideIcon;
  export const Users: LucideIcon;
  export const Wand2: LucideIcon;
  export const WandSparkles: LucideIcon;
  export const X: LucideIcon;
  export const Zap: LucideIcon;
}
