"use client";

import { Eye, FileText, MessageSquare, MoreHorizontal, Pin, PinOff, X } from "lucide-react";
import { useState } from "react";
import { projectOptions, workspaceTasks } from "../../lib/workbench/mockWorkspace";
import type { WorkbenchTask } from "../../modules/types";
import { CompactSelect, WorkspaceAssistant } from "./ShellControls";
import { useDismissableLayer } from "./useDismissableLayer";

export function TaskList({ pinnedItemIds, onTogglePinnedItem, onStartTask, onOpenTask }: { pinnedItemIds: string[]; onTogglePinnedItem: (id: string) => void; onStartTask: () => void; onOpenTask: (task: WorkbenchTask) => void }) {
  const [project, setProject] = useState("全部项目"); const [coworker, setCoworker] = useState("全部同事"); const [status, setStatus] = useState("全部状态"); const [selected, setSelected] = useState<WorkbenchTask | null>(null);
  const visible = workspaceTasks.all.filter((task) => (project === "全部项目" || task.project === project) && (coworker === "全部同事" || task.coworkerName === coworker) && (status === "全部状态" || task.status === status));
  return <section className="workbenchView taskWorkbenchView"><header><div><h1>我的待办</h1></div><button className="primaryButton compact" type="button" onClick={onStartTask}>新建任务</button></header><div className="taskQueueShell"><section className="taskQueueSection"><h2>待我处理 · {workspaceTasks.actionRequired.length}</h2><div className="workbenchTaskList">{workspaceTasks.actionRequired.map((task) => <TaskRow key={task.id} task={task} actionRequired pinned={pinnedItemIds.includes(task.id)} onPin={() => onTogglePinnedItem(task.id)} onPreview={() => setSelected(task)} onEnter={() => onOpenTask(task)} />)}</div></section><section className="taskQueueSection"><div className="taskSectionHeader"><h2>全部任务</h2><div className="taskFilters"><CompactSelect value={project} options={["全部项目", ...projectOptions]} onChange={setProject} /><CompactSelect value={coworker} options={["全部同事", "肿瘤报告同事", "DMPK报价同事"]} onChange={setCoworker} /><CompactSelect value={status} options={["全部状态", "处理中", "已完成", "待确认", "临时任务"]} onChange={setStatus} /></div></div><div className="workbenchTaskList allTaskList">{visible.map((task) => <TaskRow key={task.id} task={task} pinned={pinnedItemIds.includes(task.id)} onPin={() => onTogglePinnedItem(task.id)} onPreview={() => setSelected(task)} onEnter={() => onOpenTask(task)} />)}{!visible.length ? <div className="emptyListState">没有符合当前筛选条件的任务</div> : null}</div></section></div><WorkspaceAssistant context="tasks" onStartTask={onStartTask} />{selected ? <TaskPreview task={selected} onClose={() => setSelected(null)} onOpen={() => { onOpenTask(selected); setSelected(null); }} /> : null}</section>;
}

function TaskRow({ task, actionRequired = false, pinned, onPin, onPreview, onEnter }: { task: WorkbenchTask; actionRequired?: boolean; pinned: boolean; onPin: () => void; onPreview: () => void; onEnter: () => void }) { const [open, setOpen] = useState(false); const ref = useDismissableLayer<HTMLElement>(open, () => setOpen(false)); return <article ref={ref} className={`workbenchTaskCard ${actionRequired ? "actionRequired" : ""} ${open ? "selected" : ""}`} onContextMenu={(event) => { event.preventDefault(); setOpen(true); }}><button className="taskRowMain" type="button" onClick={onPreview}><FileText size={16} strokeWidth={1.8} /><span><strong>{task.title}</strong><small>{task.project} · {task.coworkerName} · {task.time}</small></span></button><em>{task.status}</em><button className="rowMoreButton" type="button" aria-label={`${task.title}更多操作`} onClick={() => setOpen((value) => !value)}><MoreHorizontal size={15} /></button>{open ? <div className="rowActionMenu"><button type="button" onClick={() => { onPreview(); setOpen(false); }}><Eye size={14} />预览任务</button><button type="button" onClick={() => { onPin(); setOpen(false); }}>{pinned ? <PinOff size={14} /> : <Pin size={14} />}{pinned ? "取消置顶" : "置顶任务"}</button><button type="button" onClick={() => { onEnter(); setOpen(false); }}><MessageSquare size={14} />进入会话</button></div> : null}</article>; }

function TaskPreview({ task, onClose, onOpen }: { task: WorkbenchTask; onClose: () => void; onOpen: () => void }) { return <div className="modalBackdrop taskPreviewBackdrop" role="dialog" aria-modal="true"><section className="taskPreviewDialog"><header><div><span>{task.project}</span><h2>{task.title}</h2></div><button className="iconButton" type="button" onClick={onClose} aria-label="关闭"><X size={17} /></button></header><div className="taskPreviewBody"><dl><div><dt>状态</dt><dd>{task.status}</dd></div><div><dt>数字同事</dt><dd>{task.coworkerName}</dd></div><div><dt>最近更新</dt><dd>{task.time}</dd></div></dl><section><h3>最近进展</h3><p>任务上下文和相关项目文件已就绪。</p></section></div><footer><button className="secondaryButton compact" type="button" onClick={onClose}>关闭</button><button className="primaryButton compact" type="button" onClick={onOpen}>进入任务会话</button></footer></section></div>; }
