"use client";

import { BadgeDollarSign, Check, ChevronRight, ChevronUp, Eye, FileText, Folder, LogOut, MoreHorizontal, Orbit, PanelRight, Pin, PinOff, Plus, Search, Settings, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { workspacePinCatalog, workspaceProjects } from "../../lib/workbench/mockWorkspace";
import type { PinItem } from "../../lib/workbench/shellTypes";
import type { WorkbenchProject, WorkbenchRoute, WorkbenchTask } from "../../modules/types";
import { useDismissableLayer } from "./useDismissableLayer";

type Props = { collapsed: boolean; activeRoute: WorkbenchRoute; activeTaskId: string | null; currentProject: string | null; projects: WorkbenchProject[]; runtimeTasks: WorkbenchTask[]; pinnedItemIds: string[]; onCreateProject: (name: string) => WorkbenchProject | null; onTogglePinnedItem: (id: string) => void; onRouteChange: (route: Exclude<WorkbenchRoute, "module">) => void; onStartTask: (project?: string | null) => void; onOpenTask: (task: WorkbenchTask) => void; onOpenQuotationManagement: () => void; onToggleCollapsed: () => void };

export function WorkspaceSidebar(props: Props) {
  const [openProjects, setOpenProjects] = useState<Record<string, boolean>>({ "project-xx": true, "project-yy": true, "project-zz": false });
  const [searchOpen, setSearchOpen] = useState(false);
  const [projectCreateOpen, setProjectCreateOpen] = useState(false);
  const [projectDraft, setProjectDraft] = useState("");
  const [accountMenuOpen, setAccountMenuOpen] = useState(false);
  const accountRef = useDismissableLayer<HTMLDivElement>(accountMenuOpen, () => setAccountMenuOpen(false));
  const runtimePinItems: PinItem[] = props.runtimeTasks.map((task) => ({ ...task, type: "task" }));
  const catalog: PinItem[] = [...runtimePinItems, ...workspacePinCatalog];
  const pinnedItems = props.pinnedItemIds.map((id) => catalog.find((item) => item.id === id)).filter((item): item is PinItem => Boolean(item));
  const activeProject = props.activeTaskId ? props.currentProject : null;
  const startTask = (project: string | null = null) => props.onStartTask(project);
  const commitProject = () => {
    const created = props.onCreateProject(projectDraft);
    if (!created) return;
    setOpenProjects((current) => ({ ...current, [created.id]: true }));
    setProjectDraft("");
    setProjectCreateOpen(false);
  };
  const openItem = (item: PinItem) => item.type === "project" ? startTask(item.title) : props.onOpenTask(toTask(item));
  return <aside className="sidebar">
    <div className="brand"><img src="/logo/bioaz-logo.svg" alt="" /><span>BioAZ</span><button className="sidebarCollapseButton" type="button" onClick={props.onToggleCollapsed} aria-label={props.collapsed ? "展开侧边栏" : "折叠侧边栏"}><PanelRight size={17} /></button></div>
    <div className="sidebarActions">{searchOpen ? <div className="sidebarSearch"><Search size={15} /><input autoFocus placeholder="搜索任务、项目" /><button type="button" onClick={() => setSearchOpen(false)} aria-label="关闭搜索"><X size={14} /></button></div> : <><button className="newChat" type="button" title={activeProject ? `在 ${activeProject} 中新建任务` : "新建任务"} onClick={() => startTask(activeProject)}><span>+</span>新建任务</button><button className="sidebarSearchButton" type="button" onClick={() => setSearchOpen(true)} aria-label="搜索"><Search size={17} /></button></>}</div>
    <nav className="navBlock workspaceViews" aria-label="工作区"><button className={`workspaceViewRow ${props.activeRoute === "library" ? "active" : ""}`} type="button" onClick={() => props.onRouteChange("library")}><Orbit size={15} strokeWidth={1.8} /><span>智能项目中枢</span></button></nav>
    {pinnedItems.length ? <section className="navBlock pinnedBlock" aria-label="置顶"><p>置顶</p>{pinnedItems.map((item) => item.type === "project" ? <PinnedProject key={item.id} title={item.title} onClick={() => openItem(item)} onUnpin={() => props.onTogglePinnedItem(item.id)} /> : <SidebarTask key={item.id} item={item} active={props.activeTaskId === item.id} pinned onClick={() => openItem(item)} onPinToggle={() => props.onTogglePinnedItem(item.id)} />)}</section> : null}
    <nav className="navBlock projectTree" aria-label="项目"><div className="navSectionHeader"><span>项目</span><button type="button" aria-label="新建项目" title="新建项目" onClick={() => setProjectCreateOpen(true)}><Plus size={14} /></button></div>{projectCreateOpen ? <div className="projectCreateRow"><Folder size={14} /><input autoFocus value={projectDraft} onChange={(event) => setProjectDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") commitProject(); if (event.key === "Escape") { setProjectCreateOpen(false); setProjectDraft(""); } }} placeholder="项目名称" aria-label="项目名称" /><button type="button" disabled={!projectDraft.trim()} onClick={commitProject} aria-label="确认新建项目"><Check size={14} /></button><button type="button" onClick={() => { setProjectCreateOpen(false); setProjectDraft(""); }} aria-label="取消"><X size={13} /></button></div> : null}{props.projects.map((project) => <SidebarProject key={project.id} title={project.name} open={Boolean(openProjects[project.id])} pinned={props.pinnedItemIds.includes(project.id)} onTogglePin={() => props.onTogglePinnedItem(project.id)} onToggle={() => setOpenProjects((current) => ({ ...current, [project.id]: !current[project.id] }))}>{catalog.filter((item) => item.type === "task" && item.project === project.name).map((item) => <SidebarTask key={item.id} item={item} active={props.activeTaskId === item.id} pinned={props.pinnedItemIds.includes(item.id)} onPinToggle={() => props.onTogglePinnedItem(item.id)} onClick={() => props.onOpenTask(toTask(item))} />)}</SidebarProject>)}</nav>
    <div ref={accountRef} className={`account accountMenuTrigger ${accountMenuOpen ? "menuOpen" : ""}`}><button type="button" onClick={() => setAccountMenuOpen((value) => !value)} aria-expanded={accountMenuOpen}><span className="avatar">A</span><span><strong>Admin</strong><small>admin@example.com</small></span><ChevronUp size={15} /></button>{accountMenuOpen ? <div className="accountMenu"><div><span className="avatar">A</span><span><strong>Admin</strong><small>admin@example.com</small></span></div><button type="button"><Settings size={15} />账户设置</button><button className="quotationManagementEntry" type="button" onClick={() => { setAccountMenuOpen(false); props.onOpenQuotationManagement(); }}><BadgeDollarSign size={15} />报价管理</button><button type="button"><LogOut size={15} />退出登录</button></div> : null}</div>
  </aside>;
}

function toTask(item: PinItem): WorkbenchTask { return { id: item.id, title: item.title, project: item.project ?? "临时任务", moduleId: item.moduleId ?? "dmpk-quotation", coworkerId: item.coworkerId ?? "dmpk-quotation-coworker", coworkerName: item.coworkerName ?? "DMPK报价同事", time: item.time ?? "", status: item.status ?? "" }; }

function PinnedProject({ title, onClick, onUnpin }: { title: string; onClick: () => void; onUnpin: () => void }) { const [open, setOpen] = useState(false); const ref = useDismissableLayer<HTMLDivElement>(open, () => setOpen(false)); return <div ref={ref} className="pinnedProjectRow"><button type="button" onClick={onClick}><Folder size={15} /><strong>{title}</strong></button><button type="button" aria-label="置顶项目操作" onClick={() => setOpen((value) => !value)}><MoreHorizontal size={14} /></button>{open ? <div className="sidebarMenu"><button type="button" onClick={() => { onUnpin(); setOpen(false); }}><PinOff size={14} />取消置顶</button></div> : null}</div>; }

function SidebarProject({ title, open, pinned, onTogglePin, onToggle, children }: { title: string; open: boolean; pinned: boolean; onTogglePin: () => void; onToggle: () => void; children: ReactNode }) { const [menuOpen, setMenuOpen] = useState(false); const ref = useDismissableLayer<HTMLDivElement>(menuOpen, () => setMenuOpen(false)); return <div className="projectGroup"><div ref={ref} className={`projectRowWrap ${menuOpen ? "menuOpen" : ""}`} onContextMenu={(event) => { event.preventDefault(); setMenuOpen(true); }}><button className="projectRow" type="button" onClick={onToggle}><Folder size={15} strokeWidth={1.8} /><strong>{title}</strong><ChevronRight className={open ? "isOpen" : ""} size={14} strokeWidth={1.8} /></button><div className="projectHoverActions isActionOnly"><button type="button" aria-label="项目操作" onClick={(event) => { event.stopPropagation(); setMenuOpen((value) => !value); }}><MoreHorizontal size={14} /></button>{menuOpen ? <div className="sidebarMenu projectMenu"><button type="button" onClick={() => { onTogglePin(); setMenuOpen(false); }}>{pinned ? <PinOff size={14} /> : <Pin size={14} />}{pinned ? "取消置顶" : "置顶项目"}</button></div> : null}</div></div>{open ? <div className="chatTree">{children}</div> : null}</div>; }

function SidebarTask({ item, active = false, pinned = false, archiveable = false, onClick, onPinToggle }: { item: (typeof workspacePinCatalog)[number]; active?: boolean; pinned?: boolean; archiveable?: boolean; onClick: () => void; onPinToggle: () => void }) { const [menuOpen, setMenuOpen] = useState(false); const [archiveOpen, setArchiveOpen] = useState(false); const ref = useDismissableLayer<HTMLDivElement>(menuOpen, () => { setMenuOpen(false); setArchiveOpen(false); }); return <div ref={ref} className={`chatRow status-${item.status ?? "done"} ${active ? "active" : ""} ${pinned ? "isPinnedShortcut" : ""} ${menuOpen ? "menuOpen" : ""}`} onContextMenu={(event) => { event.preventDefault(); setMenuOpen(true); }}><button className="chatRowMain" type="button" onClick={onClick}><FileText className="sidebarIcon" size={15} strokeWidth={1.8} /><strong>{item.title}</strong><small>{item.time}</small></button><button className="chatMoreButton" type="button" aria-label={`${item.title}更多操作`} onClick={() => setMenuOpen((value) => !value)}><MoreHorizontal size={14} /></button>{menuOpen ? <div className="sidebarMenu chatMenu"><button type="button" onClick={() => { onPinToggle(); setMenuOpen(false); }}>{pinned ? <PinOff size={14} /> : <Pin size={14} />}{pinned ? "取消置顶" : "置顶任务"}</button><button type="button" onClick={() => { onClick(); setMenuOpen(false); }}><Eye size={14} />打开任务</button>{archiveable ? <button type="button" onClick={() => setArchiveOpen((value) => !value)}><Folder size={14} />归档到项目<ChevronRight size={13} /></button> : null}{archiveable && archiveOpen ? <div className="archiveSubmenu">{workspaceProjects.map((project) => <button type="button" key={project.id} onClick={() => { setArchiveOpen(false); setMenuOpen(false); }}>{project.name}</button>)}</div> : null}</div> : null}</div>; }
